In [38]:
# numpy is python library which is universal standard for working with numerical data in python
# numpy library is contains multi dimensional arrays and matrix data structures and 
# can be used to perform wide variety of mathmetical operations on arrays
# in python we have list that can perform the purpose of arrays but they are slow
# numpy aims to provides an array object that is up to 50x faster than traditional lists
# the array object in ndarray,it provides alot of supporting functions that make working with ndarray very easy
# arrays are used in data science,where speed and resources are important
# numpy arrays are stored one continues place in memory unlike lists,so process access them and manipulate them very efficiently
import numpy as np
# now creating 1d array in numpy
a1d=np.array([1,2,3,4,5])
print('1 d array :',a1d)
print(type(a1d))
# now passing tuple to numpy arrray so tuple become array
a1=np.array((10,12,'passing tuple'))
print(a1,type(a1))
t1=(1000,3000,400)
a2=np.array(t1)#no i passed tuple var name to array
print(a2)
# ndim check the dimension of array
print('1 dimenisional array =',a2.ndim)
a23=np.array(30)
print('Zero dimenision array =',a23.ndim)
# 2d array or 2 dimenisional array
# for creating 2 dimenision array we need to give equal values or element in both array parts
a2d=np.array([[10,'person',34,56,78,89],[1000,33000,56000,4,5,6]])
print('Two dimension array',a2d)
print('Dimension of array =',a2d.ndim)
# creating 3d array 
a3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('3 dimenision array',a3d)
print('dimenision of array =',a3d.ndim)
# we can create n dimenision numbers of array
a4d=np.array([[[[1,2,3,4],[5,6,7,8]],[[10,11,12,13],[14,15,16,17]]],[[[18,19,20,21],[22,23,24,25]],[[26,27,28,29],[30,31,32,33]]]])
print('4 dimenision array ',a4d)
print('Dimenision of array =',a4d.ndim)
# indexing in array postive and negative inexing same as list
# one dimenision array inexing
print(' one dimenision value on index :',a1d[0])
# two dimenision array inexing
print('two dimenision value on index :',a2d[0])
# now i printing the value which is on the 1 index of first array of 2d arrray firs 0 represnt first array of 2d array
print('two dimenision value on index :',a2d[0,1])
# now i printing the value which is on the 2index of 2nd array of d arrray first 1 represent 2nd array of 2d array
print('two dimenision value on index :',a2d[1,2])

# three dimenision array inexing
print('three dimenision value on index :',a3d[0])
# first 0 represent first 2d of 3d array and 1 represent 2nd array of first 2d ,and 2 represnt the value on 2nd index of 2nd array
print('three dimenision value on index :',a3d[0,1,2])
# four dimenision array
print('four dimenision value on index :',a4d[0])
# first 0 represent first 33d of 4d array and 1 represent 2nd 2d of first 3d  and next represent 2nd array of 2d and 3 represent value on 3 index
print('four dimenision value on index :',a4d[0,1,1,3])

# add the first element of first array of 4d with 2nd elment of 4th array of 4d
print('print element of first array of 4d',a4d[0,0,0,0])
print(' print 2nd elment of 4th array of 4d',a4d[1,1,1,1])
print('Sum :',a4d[0,0,0,0]+a4d[1,1,1,1])


1 d array : [1 2 3 4 5]
<class 'numpy.ndarray'>
['10' '12' 'passing tuple'] <class 'numpy.ndarray'>
[1000 3000  400]
1 dimenisional array = 1
Zero dimenision array = 0
Two dimension array [['10' 'person' '34' '56' '78' '89']
 ['1000' '33000' '56000' '4' '5' '6']]
Dimension of array = 2
3 dimenision array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimenision of array = 3
4 dimenision array  [[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[10 11 12 13]
   [14 15 16 17]]]


 [[[18 19 20 21]
   [22 23 24 25]]

  [[26 27 28 29]
   [30 31 32 33]]]]
Dimenision of array = 4
 one dimenision value on index : 1
two dimenision value on index : ['10' 'person' '34' '56' '78' '89']
two dimenision value on index : person
two dimenision value on index : 56000
three dimenision value on index : [[1 2 3]
 [4 5 6]]
three dimenision value on index : 6
four dimenision value on index : [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 11 12 13]
  [14 15 16 17]]]
four dimenision value on index : 17
print element of 

In [48]:
# slicing of numpy arrays
# slicing in 1 dimenision array
ar1d=np.array([1,2,3,4,5,6,7])
print('Slicing of 1d array :',ar1d[2:4])
# 1d array slicing with steps
print('1d array slicing with steps : ',ar1d[1:5:3])
# slicing in 2 dimenision array
ar2d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print('Slicing of 2d array :',ar2d[1,0:4])
# 2d array slicing with steps
print('2d array slicing with steps : ',ar2d[1,0:5:3])
# slicing in 3 dimenision array
ar3d=np.array([[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],[[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]]])
print('Slicing of 3d array :',ar3d[1,0,0:4])
# 3d array slicing with steps
print('3d array slicing with steps : ',ar3d[1,0,0:5:3])




Slicing of 1d array : [3 4]
1d array slicing with steps :  [2 5]
Slicing of 2d array : [ 8  9 10 11]
2d array slicing with steps :  [ 8 11]
Slicing of 3d array : [15 16 17 18]
3d array slicing with steps :  [15 18]


In [58]:
# data types of numpy
# i represent integer
# b represent bolean
# u represent unassigned integer
# f represent float
# c represent complex float
# m represent timedelta
# M represent datetime
# S represent string
# U represent unicode
# V represent fixed chunk of memory(void)
# checking the data type of an array
adt=np.array([1,2,3,4])
print(adt.dtype)
adt1=np.array(['animals','dog','cat'])
print(adt1.dtype)
# create arrays with defined data type
ard=np.array([1,2,3,4],dtype='S')
print(ard)
print(ard.dtype)
# creating an array with four bytes integer
arb=np.array([123,321,423],dtype='i4')
print(arb)
print(arb.dtype)
# numpy array shape
# the shape of numpy array is number of elements in each dimenision
# now print the shape of a numpy array
asr=np.array([[1,2,3,4],[5,6,7,8]])
print(asr.shape)
# now print the shape of a 3d numpy array
a3r=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(a3r.shape)
print(a3r.ndim)



int32
<U7
[b'1' b'2' b'3' b'4']
|S1
[123 321 423]
int32
(2, 4)
(2, 2, 4)
3


In [75]:
# joining numpy arrays by concatinate function
# but concatenate same number of dimenision
ajr=np.concatenate((adt1,arb))
print(ajr)
# join 2d arrays (axis 1 means joins with row 1 of 1 array row 1 of 2nd array and same with row2)
# (axis 0 means joins by col 1 of 1 array with col1 of 2nd array and same with col 2)
a2c=np.array([[1,2,3],[3,4,5]])
a3c=np.array([[6,7,8],[9,10,11]])
ajr2=np.concatenate((a2c,a3c),axis=1)
ajr21=np.concatenate((a2c,a3c),axis=0)
print(ajr2)
print(ajr21)
# spliting numpy arrays means splting the arrays in parts
# splitting array a2c in two parts
asp=np.array_split(a2c,3)
print(asp)
# ravel and flatten fnction convert multi dimenisional array into 1d array
m=np.array([[[1,2,3,4],[6,7,8,9]],[[11,12,13,14],[15,16,17,18]]])
print(m)
# ravel convert multi dimenision into 1 dimenision
n=np.ravel(m)
print(n)
m1=np.array([[[1,2,3,4],[6,7,8,9]],[[11,12,18,14],[15,16,17,18]]])
print(m1)
# flatten convert multi dimenision into 1 dimenision(ravel and flatten both work same)
n1=m1.flatten()
print(n1)





['animals' 'dog' 'cat' '123' '321' '423']
[[ 1  2  3  6  7  8]
 [ 3  4  5  9 10 11]]
[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[array([[1, 2, 3]]), array([[3, 4, 5]]), array([], shape=(0, 3), dtype=int32)]
[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 13 14]
  [15 16 17 18]]]
[ 1  2  3  4  6  7  8  9 11 12 13 14 15 16 17 18]
[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 18 14]
  [15 16 17 18]]]
[ 1  2  3  4  6  7  8  9 11 12 18 14 15 16 17 18]


In [84]:
# Unique Fnction (tis function is used to find thhe unique value in the array)
print(m1)
un=np.unique(m1,return_index=True,return_counts=True) #retrn_index tells the index of values and return_counts tells the values how many times repeated
print(un)
# delete the item in the array
d=np.array([20,30,40,50])
print(d)
de=np.delete(d,[3])
print(de)
# how delete the row in the 3d array
print(m1)
d1=np.delete(m1,1,axis=0)
print(d1)

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 18 14]
  [15 16 17 18]]]
(array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 14, 15, 16, 17, 18]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 10],
      dtype=int64), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2], dtype=int64))
[20 30 40 50]
[20 30 40]
[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 18 14]
  [15 16 17 18]]]
[[[1 2 3 4]
  [6 7 8 9]]]
